# Generated by Django 5.2 on 2025-04-28 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='category_of_expense',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('health', 'Health'), ('housing', 'Housing'), ('entertainment', 'Entertainment'), ('transport', 'Transport'), ('travel', 'Travel'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='category_of_income',
            field=models.CharField(blank=True, choices=[('investments', 'Investments'), ('salary', 'Salary'), ('freelance', 'Freelance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
