# Generated by Django 5.2 on 2025-04-28 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_budget_category_budget_category_of_expense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=7),
        ),
    ]
